### ISSUE TITLE
Employee Out of Pocket Expense Management Module

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#133]
## Feature of the Module
1. Team Members can enter expenses in Jamku
2. An approver will approve these expenses, once approved, it will be shown in Task Billing Tab in Task View
3. An expense can be 2 types - Client Chargeable or Non-chargeable. The approver can select the type while approving the expense. Accordingly, it will affect Task Costing
4. User having appropriate permission, can mark the expense are "Reimbursed". This will help offices as well as employees to keep track of which expenses are pending to be reimbursed.

**Comment by HarshVardhan84** [comment]
Team member expenses or OPE on a Task or a client services is very much required for better office management. There should be a system of posting by employee or article and approved by a senior or immediate Team Leader. Moreover, once it is approved, there should be a concept of voucher printing in a particular approved format so that again voucher typing is not required and the Cashier or Accounts section is directed to pay only on Vouchers printed from the software for record management. 
Going further,  expenses can be both travelling lodging etc but there can be like ROC fee which is related to a particular task and is also billed/reimbursement claimed. So all expenses should a tag of reimbursable or not, if yes, the to pop-up or alert showing at the time of preparation of bill.

**Comment by adarshmadrecha** [comment]
**Update**: This module is being planned.

**Comment by ssuranaca** [comment]
Thier should be easy way to enter out of pocket expenses etc I.e.  need few clicks and no need to go multiple tabs... Like at the time of billing we can enter out of pocket expenses and Taxes paid by us for any task and/or it may also capture such info from task itself i.e. in a task during working on it their should be a area where team member can enter such amounts which incurred for respective task like Taxes or other expenses. 

Standard template must provided so that it get regulated to few names and team can easily select and enter expenses etc

Small naration space must be provided

**Comment by adarshmadrecha** [comment]
released in `v3.22.0`
