### ISSUE TITLE
Share button in Task, Client View page on Mobile

### ISSUE THREAD

**Issue by adarshmadrecha** [adarshmadrecha/jamku#205]
## Feature Request
Add a **share** ♐ button on the mobile app in Task & Client view.
So, the task link can be shared with other team members.

**Comment by adarshmadrecha** [comment]
Added share button in `v3.15.2` to `Task View`.
Keeping this open, as it is yet to be added to Client, Sub Task

**Comment by vatsalbhatia** [comment]
Share Button should be available in Web Page login as well... Mostly you work on webpage and whatsapp is running on Web.Whatsapp.com....

So either it be Share button or a button which copies the content of share button (Content which is shared when tapped on Share button in Mobile Application)

So that same can be added Pasted in Whatsapp as well.....

**Comment by yogeshkudikala** [comment]
Released in `v3.15.2`
